apiVersion: v1
kind: Service              
metadata:
  name: eth-netstats

spec:
  type: LoadBalancer
#  externalIPs:
#  - 10.7.7.203
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30420
  selector:
    app: eth-netstats
