apiVersion: v1
kind: Service              
metadata:
  name: postgresql

spec:
  type: LoadBalancer
#  externalIPs:
#  - 10.7.7.203
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30421
  selector:
    app: postgresql
